---
# tasks file for ansible-role-mbp

- name: Ensure we have homebrew itself installed
  include_tasks: homebrew_bootstrap.yml

- name: install homebrew items
  include_tasks: homebrew.yml

- name: install Mac App Store products
  include_tasks: mas.yml
